// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package org.javacs.proto;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:javacs.Config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    java.util.List<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule> 
        getImportCandidateRulesList();
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule getImportCandidateRules(int index);
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    int getImportCandidateRulesCount();
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    java.util.List<? extends org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder> 
        getImportCandidateRulesOrBuilderList();
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder getImportCandidateRulesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code javacs.Config}
   */
  public static final class Config extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:javacs.Config)
      ConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Config.newBuilder() to construct.
    private Config(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Config() {
      importCandidateRules_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Config();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                importCandidateRules_ = new java.util.ArrayList<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule>();
                mutable_bitField0_ |= 0x00000001;
              }
              importCandidateRules_.add(
                  input.readMessage(org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          importCandidateRules_ = java.util.Collections.unmodifiableList(importCandidateRules_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.javacs.proto.ConfigOuterClass.Config.class, org.javacs.proto.ConfigOuterClass.Config.Builder.class);
    }

    public interface ImportCandidateRuleOrBuilder extends
        // @@protoc_insertion_point(interface_extends:javacs.Config.ImportCandidateRule)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string missing_identifier_pattern = 1;</code>
       * @return The missingIdentifierPattern.
       */
      java.lang.String getMissingIdentifierPattern();
      /**
       * <code>string missing_identifier_pattern = 1;</code>
       * @return The bytes for missingIdentifierPattern.
       */
      com.google.protobuf.ByteString
          getMissingIdentifierPatternBytes();

      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @return A list containing the ignoreCandidatePatterns.
       */
      java.util.List<java.lang.String>
          getIgnoreCandidatePatternsList();
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @return The count of ignoreCandidatePatterns.
       */
      int getIgnoreCandidatePatternsCount();
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @param index The index of the element to return.
       * @return The ignoreCandidatePatterns at the given index.
       */
      java.lang.String getIgnoreCandidatePatterns(int index);
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the ignoreCandidatePatterns at the given index.
       */
      com.google.protobuf.ByteString
          getIgnoreCandidatePatternsBytes(int index);

      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @return A list containing the exclusiveCandidates.
       */
      java.util.List<java.lang.String>
          getExclusiveCandidatesList();
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @return The count of exclusiveCandidates.
       */
      int getExclusiveCandidatesCount();
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @param index The index of the element to return.
       * @return The exclusiveCandidates at the given index.
       */
      java.lang.String getExclusiveCandidates(int index);
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the exclusiveCandidates at the given index.
       */
      com.google.protobuf.ByteString
          getExclusiveCandidatesBytes(int index);
    }
    /**
     * Protobuf type {@code javacs.Config.ImportCandidateRule}
     */
    public static final class ImportCandidateRule extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:javacs.Config.ImportCandidateRule)
        ImportCandidateRuleOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use ImportCandidateRule.newBuilder() to construct.
      private ImportCandidateRule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private ImportCandidateRule() {
        missingIdentifierPattern_ = "";
        ignoreCandidatePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        exclusiveCandidates_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new ImportCandidateRule();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private ImportCandidateRule(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                missingIdentifierPattern_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  ignoreCandidatePatterns_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000001;
                }
                ignoreCandidatePatterns_.add(s);
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                  exclusiveCandidates_ = new com.google.protobuf.LazyStringArrayList();
                  mutable_bitField0_ |= 0x00000002;
                }
                exclusiveCandidates_.add(s);
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000001) != 0)) {
            ignoreCandidatePatterns_ = ignoreCandidatePatterns_.getUnmodifiableView();
          }
          if (((mutable_bitField0_ & 0x00000002) != 0)) {
            exclusiveCandidates_ = exclusiveCandidates_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_ImportCandidateRule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_ImportCandidateRule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.class, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder.class);
      }

      public static final int MISSING_IDENTIFIER_PATTERN_FIELD_NUMBER = 1;
      private volatile java.lang.Object missingIdentifierPattern_;
      /**
       * <code>string missing_identifier_pattern = 1;</code>
       * @return The missingIdentifierPattern.
       */
      @java.lang.Override
      public java.lang.String getMissingIdentifierPattern() {
        java.lang.Object ref = missingIdentifierPattern_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          missingIdentifierPattern_ = s;
          return s;
        }
      }
      /**
       * <code>string missing_identifier_pattern = 1;</code>
       * @return The bytes for missingIdentifierPattern.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMissingIdentifierPatternBytes() {
        java.lang.Object ref = missingIdentifierPattern_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          missingIdentifierPattern_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IGNORE_CANDIDATE_PATTERNS_FIELD_NUMBER = 2;
      private com.google.protobuf.LazyStringList ignoreCandidatePatterns_;
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @return A list containing the ignoreCandidatePatterns.
       */
      public com.google.protobuf.ProtocolStringList
          getIgnoreCandidatePatternsList() {
        return ignoreCandidatePatterns_;
      }
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @return The count of ignoreCandidatePatterns.
       */
      public int getIgnoreCandidatePatternsCount() {
        return ignoreCandidatePatterns_.size();
      }
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @param index The index of the element to return.
       * @return The ignoreCandidatePatterns at the given index.
       */
      public java.lang.String getIgnoreCandidatePatterns(int index) {
        return ignoreCandidatePatterns_.get(index);
      }
      /**
       * <code>repeated string ignore_candidate_patterns = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the ignoreCandidatePatterns at the given index.
       */
      public com.google.protobuf.ByteString
          getIgnoreCandidatePatternsBytes(int index) {
        return ignoreCandidatePatterns_.getByteString(index);
      }

      public static final int EXCLUSIVE_CANDIDATES_FIELD_NUMBER = 3;
      private com.google.protobuf.LazyStringList exclusiveCandidates_;
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @return A list containing the exclusiveCandidates.
       */
      public com.google.protobuf.ProtocolStringList
          getExclusiveCandidatesList() {
        return exclusiveCandidates_;
      }
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @return The count of exclusiveCandidates.
       */
      public int getExclusiveCandidatesCount() {
        return exclusiveCandidates_.size();
      }
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @param index The index of the element to return.
       * @return The exclusiveCandidates at the given index.
       */
      public java.lang.String getExclusiveCandidates(int index) {
        return exclusiveCandidates_.get(index);
      }
      /**
       * <code>repeated string exclusive_candidates = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the exclusiveCandidates at the given index.
       */
      public com.google.protobuf.ByteString
          getExclusiveCandidatesBytes(int index) {
        return exclusiveCandidates_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(missingIdentifierPattern_)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, missingIdentifierPattern_);
        }
        for (int i = 0; i < ignoreCandidatePatterns_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ignoreCandidatePatterns_.getRaw(i));
        }
        for (int i = 0; i < exclusiveCandidates_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, exclusiveCandidates_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(missingIdentifierPattern_)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, missingIdentifierPattern_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < ignoreCandidatePatterns_.size(); i++) {
            dataSize += computeStringSizeNoTag(ignoreCandidatePatterns_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getIgnoreCandidatePatternsList().size();
        }
        {
          int dataSize = 0;
          for (int i = 0; i < exclusiveCandidates_.size(); i++) {
            dataSize += computeStringSizeNoTag(exclusiveCandidates_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getExclusiveCandidatesList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule)) {
          return super.equals(obj);
        }
        org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule other = (org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule) obj;

        if (!getMissingIdentifierPattern()
            .equals(other.getMissingIdentifierPattern())) return false;
        if (!getIgnoreCandidatePatternsList()
            .equals(other.getIgnoreCandidatePatternsList())) return false;
        if (!getExclusiveCandidatesList()
            .equals(other.getExclusiveCandidatesList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MISSING_IDENTIFIER_PATTERN_FIELD_NUMBER;
        hash = (53 * hash) + getMissingIdentifierPattern().hashCode();
        if (getIgnoreCandidatePatternsCount() > 0) {
          hash = (37 * hash) + IGNORE_CANDIDATE_PATTERNS_FIELD_NUMBER;
          hash = (53 * hash) + getIgnoreCandidatePatternsList().hashCode();
        }
        if (getExclusiveCandidatesCount() > 0) {
          hash = (37 * hash) + EXCLUSIVE_CANDIDATES_FIELD_NUMBER;
          hash = (53 * hash) + getExclusiveCandidatesList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code javacs.Config.ImportCandidateRule}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:javacs.Config.ImportCandidateRule)
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_ImportCandidateRule_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_ImportCandidateRule_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.class, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder.class);
        }

        // Construct using org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          missingIdentifierPattern_ = "";

          ignoreCandidatePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          exclusiveCandidates_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_ImportCandidateRule_descriptor;
        }

        @java.lang.Override
        public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule getDefaultInstanceForType() {
          return org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.getDefaultInstance();
        }

        @java.lang.Override
        public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule build() {
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule buildPartial() {
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule result = new org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule(this);
          int from_bitField0_ = bitField0_;
          result.missingIdentifierPattern_ = missingIdentifierPattern_;
          if (((bitField0_ & 0x00000001) != 0)) {
            ignoreCandidatePatterns_ = ignoreCandidatePatterns_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.ignoreCandidatePatterns_ = ignoreCandidatePatterns_;
          if (((bitField0_ & 0x00000002) != 0)) {
            exclusiveCandidates_ = exclusiveCandidates_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.exclusiveCandidates_ = exclusiveCandidates_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule) {
            return mergeFrom((org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule other) {
          if (other == org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.getDefaultInstance()) return this;
          if (!other.getMissingIdentifierPattern().isEmpty()) {
            missingIdentifierPattern_ = other.missingIdentifierPattern_;
            onChanged();
          }
          if (!other.ignoreCandidatePatterns_.isEmpty()) {
            if (ignoreCandidatePatterns_.isEmpty()) {
              ignoreCandidatePatterns_ = other.ignoreCandidatePatterns_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIgnoreCandidatePatternsIsMutable();
              ignoreCandidatePatterns_.addAll(other.ignoreCandidatePatterns_);
            }
            onChanged();
          }
          if (!other.exclusiveCandidates_.isEmpty()) {
            if (exclusiveCandidates_.isEmpty()) {
              exclusiveCandidates_ = other.exclusiveCandidates_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureExclusiveCandidatesIsMutable();
              exclusiveCandidates_.addAll(other.exclusiveCandidates_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object missingIdentifierPattern_ = "";
        /**
         * <code>string missing_identifier_pattern = 1;</code>
         * @return The missingIdentifierPattern.
         */
        public java.lang.String getMissingIdentifierPattern() {
          java.lang.Object ref = missingIdentifierPattern_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            missingIdentifierPattern_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string missing_identifier_pattern = 1;</code>
         * @return The bytes for missingIdentifierPattern.
         */
        public com.google.protobuf.ByteString
            getMissingIdentifierPatternBytes() {
          java.lang.Object ref = missingIdentifierPattern_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            missingIdentifierPattern_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string missing_identifier_pattern = 1;</code>
         * @param value The missingIdentifierPattern to set.
         * @return This builder for chaining.
         */
        public Builder setMissingIdentifierPattern(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          missingIdentifierPattern_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string missing_identifier_pattern = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearMissingIdentifierPattern() {
          
          missingIdentifierPattern_ = getDefaultInstance().getMissingIdentifierPattern();
          onChanged();
          return this;
        }
        /**
         * <code>string missing_identifier_pattern = 1;</code>
         * @param value The bytes for missingIdentifierPattern to set.
         * @return This builder for chaining.
         */
        public Builder setMissingIdentifierPatternBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          missingIdentifierPattern_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList ignoreCandidatePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureIgnoreCandidatePatternsIsMutable() {
          if (!((bitField0_ & 0x00000001) != 0)) {
            ignoreCandidatePatterns_ = new com.google.protobuf.LazyStringArrayList(ignoreCandidatePatterns_);
            bitField0_ |= 0x00000001;
           }
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @return A list containing the ignoreCandidatePatterns.
         */
        public com.google.protobuf.ProtocolStringList
            getIgnoreCandidatePatternsList() {
          return ignoreCandidatePatterns_.getUnmodifiableView();
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @return The count of ignoreCandidatePatterns.
         */
        public int getIgnoreCandidatePatternsCount() {
          return ignoreCandidatePatterns_.size();
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @param index The index of the element to return.
         * @return The ignoreCandidatePatterns at the given index.
         */
        public java.lang.String getIgnoreCandidatePatterns(int index) {
          return ignoreCandidatePatterns_.get(index);
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @param index The index of the value to return.
         * @return The bytes of the ignoreCandidatePatterns at the given index.
         */
        public com.google.protobuf.ByteString
            getIgnoreCandidatePatternsBytes(int index) {
          return ignoreCandidatePatterns_.getByteString(index);
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @param index The index to set the value at.
         * @param value The ignoreCandidatePatterns to set.
         * @return This builder for chaining.
         */
        public Builder setIgnoreCandidatePatterns(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureIgnoreCandidatePatternsIsMutable();
          ignoreCandidatePatterns_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @param value The ignoreCandidatePatterns to add.
         * @return This builder for chaining.
         */
        public Builder addIgnoreCandidatePatterns(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureIgnoreCandidatePatternsIsMutable();
          ignoreCandidatePatterns_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @param values The ignoreCandidatePatterns to add.
         * @return This builder for chaining.
         */
        public Builder addAllIgnoreCandidatePatterns(
            java.lang.Iterable<java.lang.String> values) {
          ensureIgnoreCandidatePatternsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, ignoreCandidatePatterns_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearIgnoreCandidatePatterns() {
          ignoreCandidatePatterns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string ignore_candidate_patterns = 2;</code>
         * @param value The bytes of the ignoreCandidatePatterns to add.
         * @return This builder for chaining.
         */
        public Builder addIgnoreCandidatePatternsBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureIgnoreCandidatePatternsIsMutable();
          ignoreCandidatePatterns_.add(value);
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList exclusiveCandidates_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        private void ensureExclusiveCandidatesIsMutable() {
          if (!((bitField0_ & 0x00000002) != 0)) {
            exclusiveCandidates_ = new com.google.protobuf.LazyStringArrayList(exclusiveCandidates_);
            bitField0_ |= 0x00000002;
           }
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @return A list containing the exclusiveCandidates.
         */
        public com.google.protobuf.ProtocolStringList
            getExclusiveCandidatesList() {
          return exclusiveCandidates_.getUnmodifiableView();
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @return The count of exclusiveCandidates.
         */
        public int getExclusiveCandidatesCount() {
          return exclusiveCandidates_.size();
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @param index The index of the element to return.
         * @return The exclusiveCandidates at the given index.
         */
        public java.lang.String getExclusiveCandidates(int index) {
          return exclusiveCandidates_.get(index);
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @param index The index of the value to return.
         * @return The bytes of the exclusiveCandidates at the given index.
         */
        public com.google.protobuf.ByteString
            getExclusiveCandidatesBytes(int index) {
          return exclusiveCandidates_.getByteString(index);
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @param index The index to set the value at.
         * @param value The exclusiveCandidates to set.
         * @return This builder for chaining.
         */
        public Builder setExclusiveCandidates(
            int index, java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureExclusiveCandidatesIsMutable();
          exclusiveCandidates_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @param value The exclusiveCandidates to add.
         * @return This builder for chaining.
         */
        public Builder addExclusiveCandidates(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  ensureExclusiveCandidatesIsMutable();
          exclusiveCandidates_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @param values The exclusiveCandidates to add.
         * @return This builder for chaining.
         */
        public Builder addAllExclusiveCandidates(
            java.lang.Iterable<java.lang.String> values) {
          ensureExclusiveCandidatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, exclusiveCandidates_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearExclusiveCandidates() {
          exclusiveCandidates_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string exclusive_candidates = 3;</code>
         * @param value The bytes of the exclusiveCandidates to add.
         * @return This builder for chaining.
         */
        public Builder addExclusiveCandidatesBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          ensureExclusiveCandidatesIsMutable();
          exclusiveCandidates_.add(value);
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:javacs.Config.ImportCandidateRule)
      }

      // @@protoc_insertion_point(class_scope:javacs.Config.ImportCandidateRule)
      private static final org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule();
      }

      public static org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<ImportCandidateRule>
          PARSER = new com.google.protobuf.AbstractParser<ImportCandidateRule>() {
        @java.lang.Override
        public ImportCandidateRule parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ImportCandidateRule(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<ImportCandidateRule> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ImportCandidateRule> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int IMPORT_CANDIDATE_RULES_FIELD_NUMBER = 1;
    private java.util.List<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule> importCandidateRules_;
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule> getImportCandidateRulesList() {
      return importCandidateRules_;
    }
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder> 
        getImportCandidateRulesOrBuilderList() {
      return importCandidateRules_;
    }
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    @java.lang.Override
    public int getImportCandidateRulesCount() {
      return importCandidateRules_.size();
    }
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    @java.lang.Override
    public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule getImportCandidateRules(int index) {
      return importCandidateRules_.get(index);
    }
    /**
     * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
     */
    @java.lang.Override
    public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder getImportCandidateRulesOrBuilder(
        int index) {
      return importCandidateRules_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < importCandidateRules_.size(); i++) {
        output.writeMessage(1, importCandidateRules_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < importCandidateRules_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, importCandidateRules_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.javacs.proto.ConfigOuterClass.Config)) {
        return super.equals(obj);
      }
      org.javacs.proto.ConfigOuterClass.Config other = (org.javacs.proto.ConfigOuterClass.Config) obj;

      if (!getImportCandidateRulesList()
          .equals(other.getImportCandidateRulesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getImportCandidateRulesCount() > 0) {
        hash = (37 * hash) + IMPORT_CANDIDATE_RULES_FIELD_NUMBER;
        hash = (53 * hash) + getImportCandidateRulesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.javacs.proto.ConfigOuterClass.Config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.javacs.proto.ConfigOuterClass.Config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code javacs.Config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:javacs.Config)
        org.javacs.proto.ConfigOuterClass.ConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.javacs.proto.ConfigOuterClass.Config.class, org.javacs.proto.ConfigOuterClass.Config.Builder.class);
      }

      // Construct using org.javacs.proto.ConfigOuterClass.Config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getImportCandidateRulesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (importCandidateRulesBuilder_ == null) {
          importCandidateRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          importCandidateRulesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.javacs.proto.ConfigOuterClass.internal_static_javacs_Config_descriptor;
      }

      @java.lang.Override
      public org.javacs.proto.ConfigOuterClass.Config getDefaultInstanceForType() {
        return org.javacs.proto.ConfigOuterClass.Config.getDefaultInstance();
      }

      @java.lang.Override
      public org.javacs.proto.ConfigOuterClass.Config build() {
        org.javacs.proto.ConfigOuterClass.Config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.javacs.proto.ConfigOuterClass.Config buildPartial() {
        org.javacs.proto.ConfigOuterClass.Config result = new org.javacs.proto.ConfigOuterClass.Config(this);
        int from_bitField0_ = bitField0_;
        if (importCandidateRulesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            importCandidateRules_ = java.util.Collections.unmodifiableList(importCandidateRules_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.importCandidateRules_ = importCandidateRules_;
        } else {
          result.importCandidateRules_ = importCandidateRulesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.javacs.proto.ConfigOuterClass.Config) {
          return mergeFrom((org.javacs.proto.ConfigOuterClass.Config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.javacs.proto.ConfigOuterClass.Config other) {
        if (other == org.javacs.proto.ConfigOuterClass.Config.getDefaultInstance()) return this;
        if (importCandidateRulesBuilder_ == null) {
          if (!other.importCandidateRules_.isEmpty()) {
            if (importCandidateRules_.isEmpty()) {
              importCandidateRules_ = other.importCandidateRules_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureImportCandidateRulesIsMutable();
              importCandidateRules_.addAll(other.importCandidateRules_);
            }
            onChanged();
          }
        } else {
          if (!other.importCandidateRules_.isEmpty()) {
            if (importCandidateRulesBuilder_.isEmpty()) {
              importCandidateRulesBuilder_.dispose();
              importCandidateRulesBuilder_ = null;
              importCandidateRules_ = other.importCandidateRules_;
              bitField0_ = (bitField0_ & ~0x00000001);
              importCandidateRulesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getImportCandidateRulesFieldBuilder() : null;
            } else {
              importCandidateRulesBuilder_.addAllMessages(other.importCandidateRules_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.javacs.proto.ConfigOuterClass.Config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.javacs.proto.ConfigOuterClass.Config) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule> importCandidateRules_ =
        java.util.Collections.emptyList();
      private void ensureImportCandidateRulesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          importCandidateRules_ = new java.util.ArrayList<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule>(importCandidateRules_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder> importCandidateRulesBuilder_;

      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public java.util.List<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule> getImportCandidateRulesList() {
        if (importCandidateRulesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(importCandidateRules_);
        } else {
          return importCandidateRulesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public int getImportCandidateRulesCount() {
        if (importCandidateRulesBuilder_ == null) {
          return importCandidateRules_.size();
        } else {
          return importCandidateRulesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule getImportCandidateRules(int index) {
        if (importCandidateRulesBuilder_ == null) {
          return importCandidateRules_.get(index);
        } else {
          return importCandidateRulesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder setImportCandidateRules(
          int index, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule value) {
        if (importCandidateRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.set(index, value);
          onChanged();
        } else {
          importCandidateRulesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder setImportCandidateRules(
          int index, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder builderForValue) {
        if (importCandidateRulesBuilder_ == null) {
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.set(index, builderForValue.build());
          onChanged();
        } else {
          importCandidateRulesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder addImportCandidateRules(org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule value) {
        if (importCandidateRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.add(value);
          onChanged();
        } else {
          importCandidateRulesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder addImportCandidateRules(
          int index, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule value) {
        if (importCandidateRulesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.add(index, value);
          onChanged();
        } else {
          importCandidateRulesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder addImportCandidateRules(
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder builderForValue) {
        if (importCandidateRulesBuilder_ == null) {
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.add(builderForValue.build());
          onChanged();
        } else {
          importCandidateRulesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder addImportCandidateRules(
          int index, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder builderForValue) {
        if (importCandidateRulesBuilder_ == null) {
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.add(index, builderForValue.build());
          onChanged();
        } else {
          importCandidateRulesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder addAllImportCandidateRules(
          java.lang.Iterable<? extends org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule> values) {
        if (importCandidateRulesBuilder_ == null) {
          ensureImportCandidateRulesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, importCandidateRules_);
          onChanged();
        } else {
          importCandidateRulesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder clearImportCandidateRules() {
        if (importCandidateRulesBuilder_ == null) {
          importCandidateRules_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          importCandidateRulesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public Builder removeImportCandidateRules(int index) {
        if (importCandidateRulesBuilder_ == null) {
          ensureImportCandidateRulesIsMutable();
          importCandidateRules_.remove(index);
          onChanged();
        } else {
          importCandidateRulesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder getImportCandidateRulesBuilder(
          int index) {
        return getImportCandidateRulesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder getImportCandidateRulesOrBuilder(
          int index) {
        if (importCandidateRulesBuilder_ == null) {
          return importCandidateRules_.get(index);  } else {
          return importCandidateRulesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public java.util.List<? extends org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder> 
           getImportCandidateRulesOrBuilderList() {
        if (importCandidateRulesBuilder_ != null) {
          return importCandidateRulesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(importCandidateRules_);
        }
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder addImportCandidateRulesBuilder() {
        return getImportCandidateRulesFieldBuilder().addBuilder(
            org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.getDefaultInstance());
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder addImportCandidateRulesBuilder(
          int index) {
        return getImportCandidateRulesFieldBuilder().addBuilder(
            index, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.getDefaultInstance());
      }
      /**
       * <code>repeated .javacs.Config.ImportCandidateRule import_candidate_rules = 1;</code>
       */
      public java.util.List<org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder> 
           getImportCandidateRulesBuilderList() {
        return getImportCandidateRulesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder> 
          getImportCandidateRulesFieldBuilder() {
        if (importCandidateRulesBuilder_ == null) {
          importCandidateRulesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRule.Builder, org.javacs.proto.ConfigOuterClass.Config.ImportCandidateRuleOrBuilder>(
                  importCandidateRules_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          importCandidateRules_ = null;
        }
        return importCandidateRulesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:javacs.Config)
    }

    // @@protoc_insertion_point(class_scope:javacs.Config)
    private static final org.javacs.proto.ConfigOuterClass.Config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.javacs.proto.ConfigOuterClass.Config();
    }

    public static org.javacs.proto.ConfigOuterClass.Config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Config>
        PARSER = new com.google.protobuf.AbstractParser<Config>() {
      @java.lang.Override
      public Config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Config(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Config> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Config> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.javacs.proto.ConfigOuterClass.Config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javacs_Config_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javacs_Config_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_javacs_Config_ImportCandidateRule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_javacs_Config_ImportCandidateRule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\022\006javacs\"\310\001\n\006Config\022B\n\026imp" +
      "ort_candidate_rules\030\001 \003(\0132\".javacs.Confi" +
      "g.ImportCandidateRule\032z\n\023ImportCandidate" +
      "Rule\022\"\n\032missing_identifier_pattern\030\001 \001(\t" +
      "\022!\n\031ignore_candidate_patterns\030\002 \003(\t\022\034\n\024e" +
      "xclusive_candidates\030\003 \003(\tB\022\n\020org.javacs." +
      "protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_javacs_Config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_javacs_Config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javacs_Config_descriptor,
        new java.lang.String[] { "ImportCandidateRules", });
    internal_static_javacs_Config_ImportCandidateRule_descriptor =
      internal_static_javacs_Config_descriptor.getNestedTypes().get(0);
    internal_static_javacs_Config_ImportCandidateRule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_javacs_Config_ImportCandidateRule_descriptor,
        new java.lang.String[] { "MissingIdentifierPattern", "IgnoreCandidatePatterns", "ExclusiveCandidates", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
